### ISSUE TITLE
Use UNIX time for Timestamp

### ISSUE THREAD

**Issue by tekhedd** [fedi-e2ee/public-key-directory-specification#13]
Suggestion: use UNIX time (as a JSON number) for timestamp instead of RFC9557 (or other future clarifications/extensions of/to RFC8601).

(Largely cribbed from online discussion!)

#### Advantages of RFC9557 timestamp:

- Human readable, great for debugging
- Time zone can also help with debugging (the age of messages is visible)

#### Disadvantages of RFC9557 timestamp:

- RFC makes timezone (or offset) optional, people will forget this
- Implementors will use platform RFC8601 libraries to read the field. These implementations are usuallly (always) very lax in their parsing to allow for legacy data, and will not validate the field well. This could result in reduced compatibility with other implementations.
- Time zone is personal information, which should not be exposed, and is not needed
- Time zone can make it harder to debug, when computing time offsets in your head

#### Advantages of UNIX time:

- Almost impossible to format "number" incorrectly
- Smaller
- Does not leak time zone (personal data)

##### Disadvantages of UNIX time:

- Naive implementors might use old APIs that truncate the number to 32 bits
- Not human readable

#### Justification

You don't need human readable time, really. The only times stored in the format are "current time", so the pre-epoch and post-2038 limitations are moot. Using a simpler format should improve interoperability.

**Comment by soatok** [comment]
https://3v4l.org/1uEPU
Looks like this is safe to do.

**Comment by soatok** [comment]
Proposed change is in #24
