### ISSUE TITLE
PAE LE64() vs len()

### ISSUE THREAD

**Issue by raphaelahrens** [fedi-e2ee/public-key-directory-specification#38]
If there is no reason for using big endian for the `len()` function,  would it not be better to reuse the LE64 function from pasetos PAE?
Since it is already in use.

LE64 also is considering environments like the JVM where they have no unsigned ints.

https://github.com/fedi-e2ee/public-key-directory-specification/blob/c1e47e5da487e9f348a270e6fcb9de63dfad5055/Specification.md?plain=1#L1106-L1107

**Comment by soatok** [comment]
#39 should fix this discrepancy. Thanks @raphaelahrens
