### ISSUE TITLE
Alternative to Merkle-trees

### ISSUE THREAD

**Issue by AljoschaMeyer** [fedi-e2ee/public-key-directory-specification#40]
Hi,

are you set on using a (particular) Merkle-tree-based log, or are you open to alternatives? I have some (academically) [unpublished](https://aljoscha-meyer.de/reed/assets/references/meyer2023sok.pdf) [research](https://aljoscha-meyer.de/reed/assets/references/meyer2023better.pdf) that culminates in a [transparency log design](https://aljoscha-meyer.de/reed/) that is strictly more efficient (and, arguably, also more simple) than the Merkle-tree-based scheme used in the certificate transparency RFC.

I do not want to push these ideas on this project, it just would be frustrating in the case that you stumbled upon them later and did actually agree with them. I *am* happy to answer any questions if you have any =)

Cheers,
Aljoscha

**Comment by soatok** [comment]
Briefly, yes, I'm settling on Merkle Trees.

The main motivation is to leverage the existing work going into Sigsum and related projects.

Originally I was looking at [Chronicle](https://github.com/paragonie/chronicle), and only using summary hashes for the index, but it's not widely tested and the current tooling doesn't really support their hash-chaining construction.
