### ISSUE TITLE
Consider Idempotency

### ISSUE THREAD

**Issue by jimfl** [fedi-e2ee/public-key-directory-specification#50]
Under **Concepts/Message Blocks** we have:

> Each Protocol Message **MUST** be unique. Public Key Directory servers **MUST** reject any replayed Protocol Message, even if it's otherwise valid.

Given a client designed to retry, this can cause confusion in situations where a message was successfully sent and acted upon, but no acknowledgement received by the client. The action was successful, but the client receives an error on retry. The client now has an incorrect view of the system state.

If it is safe to do so, treating identical correct messages as idempotent (optionally within a reasonable time window) gets rid of this issue.

If treating repeats as idempotent isn't safe, you could also give an error response specific to this condition

**Comment by soatok** [comment]
>If treating repeats as idempotent isn't safe, you could also give an error response specific to this condition

This was completed in an earlier commit.  Thanks @jimfl!
