### ISSUE TITLE
Merkle Root Encoding version header

### ISSUE THREAD

**Issue by raphaelahrens** [fedi-e2ee/public-key-directory-specification#53]
Currently the Merkle Root Encoding is just a base64 string.

https://github.com/fedi-e2ee/public-key-directory-specification/blob/a5c4adcf466d84e4e0f73dd5dd5b9eac4a7a679f/Specification.md?plain=1#L118-L123

I think it might be helpful if there is some form of version identifier before the string.

Maybe just `pkdv1:7TwKAbkiKCCQuCpDBV2GbkkkIDfMg2AmG7TMHqXBDJU`

Since this could reduce problems with future Merkle roots.

**Comment by soatok** [comment]
Note to future self: #58 also lets us do this without introducing some flex to our key derivation that makes collisions possible.
